### PR TITLE
Return only newly added rows and columns

### PR DESCRIPTION
**Pull request by michaelmior**
This makes calls to `add_rows` and `add_columns` return only the newly added rows and columns.
This makes it easier to incrementally construct `Problem` instances when not all of the rows and columns are created simultaneously.
The full set of rows and columns are still available by accessing the problem instance directly.

The tests still pass with this change and I don't expect that this would break any existing behaviour.
If users were adding all the rows or columns at once before, this will behave in exactly the same way.

### CODE REVIEW

**Comment by wtaysom** [comment]
Thanks again Michael.  I'm glad you're getting good use out of Rglpk.

**Comment by michaelmior** [comment]
Thank you for being so quick to merge :) Would you consider releasing a new version of the gem with this change? Would save me from having to use the gem directly from git.

**Comment by wtaysom** [comment]
Makes sense to me [enjoy](https://rubygems.org/gems/rglpk/versions/0.4.0).

**Comment by michaelmior** [comment]
Thanks!

**Pull request merged**
